[package]
name = "wild-splitter"
version = "0.1.0"
authors = ["alexander.montgomery <alexander.montgomery@coxautoinc.com>"]
cargo-features = ["rename-dependency"]

[dependencies]
glob = "0.3.0"
clap = "2.33.0"
dirs = "2.0.2"
lopdf = "0.24.0"
bardecoder = "0.2.1"
rayon = "1.3.0"